version: '3.8'

services:
  api:
    build: .
    container_name: api-flask-zero
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=secret
      - DB_NAME=appdb
    networks:
      - red-interna

  db:
    image: mysql:8.0
    container_name: servidor-bd-zero
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - red-interna
      - bridge

networks:
  red-interna:
    driver: bridge
  bridge:
    driver: bridge