version: '3.8'

services:
  api:
    build: .
    container_name: api-flask-zero
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=secret
      - DB_NAME=appdb
    networks:
      - red-interna
      - npm-network

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle-logs
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8888:8080"
    networks:
      - npm-network

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    volumes:
      - uptime-kuma-data:/app/data
    ports:
      - "3001:3001"
    networks:
      - npm-network
      - red-interna

  db:
    image: mysql:8.0
    container_name: servidor-bd-zero
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - red-interna

networks:
  red-interna:
    driver: bridge
  npm-network:
    external: true

volumes:
  uptime-kuma-data: